version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: university_cms_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: university_cms
      MYSQL_USER: cms_user
      MYSQL_PASSWORD: cms_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped
    networks:
      - cms_network

volumes:
  mysql_data:

networks:
  cms_network:
    driver: bridge
